config/routes.rb
          get :exam_review_videos
          get :exam_review_textbooks
          get :exam_feedback
          get :mcq_exam_question_rating
          post :create_update_question_rating
        end
      end
    end
  end

  resources :online_exam_attempts, except: [:edit, :update] do
    collection do
      post 'create_print_exam'
    end
    member do
      get 'print_exam_questions'
      get :print_count
    end
    resources :section_attempts, only: [:index, :show] do
      resources :section_item_attempts, only: :index do
        collection do
          put 'complete'
          get 'review'
          put 'update_answer'
        end
        member do
          get :exam_review_videos
          get :exam_review_textbooks
          get :exam_feedback
          get :mcq_exam_question_rating
          post :create_update_question_rating
        end
      end
    end
  end

  resources :online_mock_exams do
    collection do
      get :archived_online_mock_exams
    end
  end
  resources :online_exams do
    member do
      get :download
      get :change_show_stat
      put :change_lock
      post :duplicate
    end
    resources :sections do
      resources :section_items do
        member do
          delete :remove_question
        end
      end
    end
    collection do
      get :check_position
      get :archived_online_exams
      post :update_product_line_positions
    end
  end

  resources :diagnostic_tests do
    member do
      get :change_show_stat
      put :change_lock
    end
    resources :sections do
      resources :section_items do
        member do
          delete :remove_question
        end
      end
    end
  end

  get 'discount/index'
  get "/exercises/:exercise_id/mcq_attempts/review" => "exercise_review#review", as: :review_exercise_exercise_review
  delete 'exercises/:exercise_id/return_to_mcq' => 'exercise_mcqs#return_to_mcq', as: :return_to_mcq
  post 'exercises/:id/repeat' => 'exercise_mcqs#repeat', as: :repeat
  post 'exercises/review_questions' => 'exercise_mcqs#review_questions', as: :review_questions
  resources :exercises do
    resources :exercise_review, except: [:new, :edit, :create, :edit, :update, :destroy] do
      member do
        get :exercise_review_videos
        get :exercise_review_textbooks
        get :give_feedback
        get :mcq_exam_question_rating
        post :create_update_question_rating
      end
    end
    resources :mcq_attempts, except: [:new, :edit, :create,
            :edit, :update, :destroy] do
      collection do
        put 'update_answer'
        put 'update_mcq_answer'
      end
    end
  end

  resources :job_application_forms, :path => 'jobs' do
    resources :job_applications, :path => 'job-applications' do
      get 'download_all', on: :collection
      get 'get_tag_childrens', on: :collection
      get 'download', on: :member
    end

    get 'archived_jobs', on: :collection
    get 'available-positions', to: 'job_application_forms#available_positions', on: :collection

    get 'show_available_position', on: :member
  end
  resources :job_applications, :path => 'job-applications', only: [] do
    get 'search_applications', on: :collection
    post 'update_interview_date', on: :collection
  end

  # resources :features
  resources :master_features do
    post :master_feature_tags, on: :collection
  end
  # get 'enrolment/:id/' => 'enrolments#show'
  resources :enrolments, only: [:show] do
    member do
      get :student_addon_enrolment
      get :transfer_by
      patch :unenrol_or_renrol
    end
    collection do
      put :attach_enrolment_details
    end
  end

  resources :common_contents, except: [:show, :index]
  resources :free_study_buddies
  resources :study_buddies
  resources :countdown_timers
  resources :download_hit_counters, only: [:index, :edit, :update]
  get 'courses/public_course_cities' => 'courses_filter#public_course_cities'
  get 'courses/filtered_product_versions' => 'courses_filter#filtered_product_versions'
  get 'courses/filtered_transfer_courses' => 'courses_filter#filtered_transfer_courses'

  get 'courses/list_cities' => 'courses_filter#list_cities'
  get 'courses/list_course_lessons' => 'courses_filter#list_course_lessons'
  get 'courses/list_courses_by_city' => 'courses_filter#list_courses_by_city'
  resources :courses do
    get 'enrolments/enrol' => 'enrolments#enrol'
    get 'enrolments/discount_course_enrolment'=> 'enrolments#discount_course_enrolment'
    get 'enrolments/quick_enrol' => 'enrolments#quick_enrol'
    get 'enrolments/student_course_enrolment' => 'enrolments#student_course_enrolment'
    post 'enrolments/paypal_payment' => 'enrolments#paypal_payment'
    post 'enrolments/transfer_payment' => 'enrolments#transfer_payment'
    get 'enrolments/cancel' => 'enrolments#cancel'
    get 'enrolments/transfer_course' => 'enrolments#transfer_course'
    get 'enrolments/custom_enrol' => 'enrolments#custom_enrol'
    
    get :trial_enabled, on: :member
    collection do
      post :set_current_course
      get :archived_courses
      get :get_course_type
    end
    member do
      post :duplicate
      post :unarchived
      get :update_course_id
      get :get_addons
    end
  end
  
  resources :transfer_transactions do
    collection do
      get '/transfer_transaction' => 'transfer_transaction#show'
    end
  end

  get '/users/view_as/:user_id' => 'users#become', as: :view_as
  resources :users, except: [:show, :index] do
    collection do
      get :check_email
      get :check_username
      get :reset_ol_exam
      get :reset_diganostic
      get :reset_essay
      get :reset_mock_exam
      delete :destroy_all
      delete :destroy_ongoing_orders
      get :verify_users
      get :cancel_appointment
      post :study_guide
      post :free_gamsat_trial
      get :reset_online_mock_exam_attempt
      get :display_expiry_date
    end
    resources :enrolments, except: [:index, :show] do
    end
    member do
      get :transfer_data
      put :deactivate
      put :resend_invitation
      get :reset_exams
      get :update_contact
      put :save_detail
      get :course_details
      post :transfer
      get :tutor_interaction_logs
    end
    post :generate_new_password_email
    # get 'enrolments'=> 'user_enrolments#index'
  end

  devise_for :users, skip: [:registrations], path: '/', path_names: {
      sign_in: 'login', sign_out: 'sign_out', password: 'login/forgotpassword'}, controllers: { invitations: 'users/invitations', sessions: 'users/sessions', confirmations: 'users/confirmations', passwords: 'users/passwords'}

  devise_scope :user do
    # devise path inherit
    get '/cancel' => 'users/registrations#cancel', as: :cancel_user_registration
    post '/register' => 'users/registrations#create', as: :user_registration
    put '/edit' => 'users/registrations#update', as: :user_update
    get '/register' => 'users/registrations#new', as: :new_user_registration
    get '/edit' => 'users/registrations#edit', as: :edit_user_registration
    patch '/' => 'users/registrations#update'
    put '/' => 'users/registrations#update'
    delete '/' => 'users/registrations#destroy'

    get "/login/forgotpassword" => "users/passwords#new"
    get '/auth/is_signed_in' => 'users/sessions#is_signed_in', as: :is_signed_in
    get '/auth' => 'users/sessions#new'
    get '/auth/password' => 'devise/passwords#new'
  end

  get '/sign_in', to: redirect("/login")
  get '/gamsat-preparation-courses/about', to: redirect("/gamsat-preparation-courses/overview")
  get '/about', to: redirect("/gamsat-preparation-courses/overview")

  get '/gamsat-preparation-courses/online-basic', to: redirect{ |params, request| "/gamsat-preparation-courses/online-essentials?#{request.params.to_query}"}
  get '/gamsat-preparation-courses/online', to: redirect{ |params, request| "/gamsat-preparation-courses/online-comprehensive?#{request.params.to_query}"}
  get '/gamsat-preparation-courses/attendence-basic', to:redirect{ |params, request| "/gamsat-preparation-courses/attendance-essentials?#{request.params.to_query}"}
  get '/gamsat-preparation-courses/attendence-d4588d4f-d803-4a68-8b06-06c2af9406ee', to: redirect{ |params, request| "/gamsat-preparation-courses/attendance-comprehensive?#{request.params.to_query}"}
  get '/gamsat-preparation-courses/attendence-all', to: redirect{ |params, request| "/gamsat-preparation-courses/attendance-complete-care?#{request.params.to_query}"}
  get '/umat-preparation-courses/online', to: redirect{ |params, request| "/umat-preparation-courses/online-comprehensive?#{request.params.to_query}"}
  get '/gamsat-preparation-courses/interviewready-comprehensive', to: redirect{ |params, request| "/gamsat-preparation-courses/interview-attendance-comprehensive?#{request.params.to_query}"}
  get '/gamsat-preparation-courses/interviewready-essentials', to: redirect{ |params, request| "/gamsat-preparation-courses/interview-attendance-essentials?#{request.params.to_query}"}
  get '/gamsat-preparation-courses/interviewready-online-essentials', to: redirect{ |params, request| "/gamsat-preparation-courses/interview-online-essentials?#{request.params.to_query}"}
  get '/gamsat-preparation-courses/1-week-trial', to: redirect{ |params, request| "/gamsat-preparation-courses/free-trial?#{request.params.to_query}"}
  get '/gamsat-preparation-courses/attendence', to: redirect{ |params, request| "/gamsat-preparation-courses/attendance-comprehensive?#{request.params.to_query}"}

  get '/umat-preparation-courses/courses-oe', to: redirect{ |params, request| "/umat-preparation-courses/online-essentials?#{request.params.to_query}"}
  get '/umat-preparation-courses/courses-oc', to: redirect{ |params, request| "/umat-preparation-courses/online-comprehensive?#{request.params.to_query}"}
  get '/umat-preparation-courses/courses-ae', to: redirect{ |params, request| "/umat-preparation-courses/attendance-essentials?#{request.params.to_query}"}

app/helpers/enrolments_helper.rb
module EnrolmentsHelper
  def available_product_line
    ProductLine.order(:name).map { |product_line| [product_line.name.capitalize,product_line.name.capitalize]}
  end
  def available_product_version
    ProductVersion.all.map{|p| [p.name, p.id]}.sort_by { |name, id| name }
  end

  def available_city
    Course.options_for_city
  end

  def enrolment_status_change_button(enrolment, student)
    if enrolment.Unenrolled?
      link_to 'Re-enroll', unenrol_or_renrol_enrolment_path(enrolment, new_state: enrolment.previous_state_before_unenrolled || 'Applied', user_id: student.id), method: :patch, data: { confirm: 'Are you sure?' }, class: 'btn btn-success btn-sm'
    else
      link_to 'Unenroll', unenrol_or_renrol_enrolment_path(enrolment, new_state: 'Unenrolled', user_id: student.id), method: :patch, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'
    end
  end

  def enrolment_status(enrolment_state, order_state)
    return 'Paid - Placeholder' if order_state == 'registered' && enrolment_state != 'Unenrolled'

    case enrolment_state
    when 'Applied'
      'Active - Paid'
    when 'Transferred'
      'Active - Transferred'
    when 'Manual Enrolment'
      'Active - New Enrolment by Staff'
    else
      enrolment_state
    end
  end
  def reset_mock_exam_select
    level = [["Section I", "section_1"], ["Section II (Essays)", "section_2"], ["Section III", "section_3"]]
  end

  def enrolment_feature_orders(enrolment, user)
    fls = FeatureLog.includes(:purchase_item).where("enrolment_id = #{enrolment.id} AND purchase_items.order_id IN (#{user.orders.ids.join(',')})").references(:purchase_item)
    fls.map{ |fl| fl.purchase_item.order_id }.uniq.reject(&:blank?)
  end

  def enrolment_invoice(enrolment, user)
    if enrolment.paid_at.present? && (current_user.admin? || current_user.superadmin?) && user.student?
      case enrolment.state
      when 'Transferred', 'Manual Enrolment'
        'No Initial Invoice Available'
      when 'Unenrolled'
        case enrolment.previous_state_before_unenrolled
        when 'Transferred', 'Manual Enrolment'
          'No Invoice Available'
        else
          link_to 'Download', enrolment_path(enrolment, format: :pdf), class: 'btn btn-default'
        end
      else
        link_to 'Download', enrolment_path(enrolment, format: :pdf), class: 'btn btn-default'
      end
    elsif enrolment.order.total_cost > 0.1
      link_to 'Download', enrolment_path(enrolment, format: :pdf), class: 'btn btn-default'
    else
      'No Initial Invoice Available'
    end
  end
end

app/views/enrolments/_course_selection_modal.haml
#courseModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "courseModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
        %h4#reassignModalLabel.modal-title Please Choose Course
      .modal-body
        %p.text-info
          %b
            .form-group
              %p
                Product Line
                = select_tag "course_product_line", options_for_select(available_product_line), { prompt: '- All -', class: 'form-control course_product_line'}

              %p
                Product Version
                = select_tag "course_product_version", options_for_select(available_product_version), { prompt: '- All -', class: 'form-control pv_select'}

              %p
                City
                = select_tag "course_city", options_for_select(available_city), { prompt: '- All -', class: 'form-control select_city'}

            .form-inputs
              Course
              = select_tag "course_id", options_for_select(Course.active_courses.order(:name).pluck(:name, :id), disabled: student.courses.ids), { prompt: 'Please Select Course', class: 'form-control chosen-select'}
            .form-actions.text-center.select_course
              = link_to 'Enrol', "#", id: "enroll", class: "submit-link btn btn-primary"
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close

:javascript
  $(document).ready(function(){
    c_id = $('#course_id').val();
    $('.submit-link').attr('href', '/courses/'+c_id+'/enrolments/student_course_enrolment/?user_id='+ #{student.id});

    $('#course_id').on('change', function(){
      id = $('#course_id').val();
      $('.submit-link').attr('href', '/courses/'+id+'/enrolments/student_course_enrolment/?user_id='+ #{student.id});
    })
  })
  $("#enroll").click(function(e){
    check_course(e)
  });
  function check_course(e){

    c_id = $('#course_id').val();
    if(c_id == ""){
      alert("Please Select Course")
      e.preventDefault();
      return false;
    }
  }

  $(".course_product_line").on('change', function(){
    product_line = $(this).val();
    product_version = $(course_product_version).val();
    city = $(course_city).val();
    $.ajax({
      url: "/courses/filtered_transfer_courses",
      type: "GET",
      dataType: 'script',
      data: {product_line: product_line},
    });
  })

  $(".pv_select").on('change', function(){
    product_line = $(course_product_line).val();
    product_version = $(this).val();
    city = $(course_city).val();
    $.ajax({
      url: "/courses/filtered_transfer_courses",
      type: "GET",
      dataType: 'script',
      data: {product_line: product_line, product_version: product_version, city: city},
    });
  })

  $(".select_city").on('change', function(){
    product_line = $(course_product_line).val();
    product_version = $(course_product_version).val();
    city = $(this).val();
    $.ajax({
      url: "/courses/filtered_transfer_courses",
      type: "GET",
      dataType: 'script',
      data: {product_line: product_line, product_version: product_version, city: city},
    });
  })

app/views/enrolments/_feature_course_modal.haml
#featureCourseModal.cstm_secure_modal.modal.fade{:role => "dialog"}
  .modal-dialog
    / Modal content
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"} ×
        %h3 Purchase Course
      .modal-body
        %p Please select at least one feature.
      .modal-footer

app/views/enrolments/_index.html.haml
%h1 Listing enrolments
%table.table.table-bordered.table-hover
  %thead
    %tr
      %th User
      %th Course
      / %th PayPal Payment
      / %th PayPal Token
      %th Paid at
      %th Enrolment Status
      %th Invoice
      %th{ colspan: 3 } Actions

  %tbody
    - if enrolments.present?
      - enrolments.each do |enrolment|
        / %tr{'data-link': url_for(user_enrolment_path(student, enrolment))}
        - enrolment_features = enrolment_feature_orders(enrolment, @user)
        %tr
          %td= enrolment.try(:user).full_name
          %td= enrolment.try(:course).try(:name)
          / %td= enrolment.paypal_payment
          / %td= enrolment.paypal_token
          %td= enrolment.paid_at
          %td= enrolment_status(enrolment.state, enrolment.order&.status)
          %td
            = enrolment_invoice(enrolment, @user)
            - if enrolment_features.present?
              - enrolment_features.each do |ef|
                = link_to 'Download', invoice_pdf_order_path(ef, format: :pdf), class: 'btn btn-default', style: 'margin-top: 10px;'
          %td= link_to 'Transfer course', transfer_by_enrolment_path(id: enrolment, user_id: @user.id ), remote: :true, class: 'btn btn-success btn-sm'
          %td= link_to 'Edit', edit_user_enrolment_path(student, enrolment), class: 'btn btn-info btn-sm'
          %td= enrolment_status_change_button(enrolment, student)
          %td= link_to 'Destroy', user_enrolment_path(student, enrolment), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'

%br
#Transfer-Cousrse-Partail

/ = link_to 'Reset Exams/Essays', reset_exams_user_path(@user.id), class: 'btn btn-gr-light-green'
= link_to 'Login', view_as_path(@user), class: 'btn btn-info'
-if student.id.present?
  = link_to "New Enrolment", "#", "data-toggle" => "modal", 'data-target' => '#courseModal', id: 'course_link', class: 'btn btn-primary'

= render 'enrolments/course_selection_modal', student: student

app/views/enrolments/_product_version_tile_info.haml
%div.tooltip_hover
  %br
    #{desc}
  %br

app/views/enrolments/_product_versions_grid.haml
- product_info = send(product_line+"_product_info")
- price_label = subject ? "price_#{subject}".to_sym : :price
%ul.modal_tablist.first_col
  %li.dark_sky_up
    %a{href: dynamic_product_version_uri(product_versions[2], product_line, subject)}
      %span.right_txt_col
        %b.crs_value
          = "$ #{product_info[product_versions[2]][price_label]}"
      %span.left_bot_col
        %b
          ATTENDANCE
        %p (Essentials)
    = render "enrolments/product_version_tile_info", product_line: product_line, course: trial_course, desc: "Essential live tutorials and online study tools. Online Essentials package, plus 31 hrs of live classroom tutorials and a mock exam day"
  %li.dark_green_up
    %a{href: dynamic_product_version_uri(product_versions[3], product_line, subject)}
      %span.right_txt_col
        %b.crs_value
          = "$ #{product_info[product_versions[3]][price_label]}"
      %span.left_bot_col
        %b
          ATTENDANCE
        %p (Comprehensive)
    = render "enrolments/product_version_tile_info", product_line: product_line, course: trial_course, desc: "A comprehensive suite of classes and online study tools with online tutor support. Attendance Essentials package, plus 6 online exams, online tutor access and 10 marked essays."
  %li.dark_blue_up
    %a{href: dynamic_product_version_uri(product_versions[4], product_line, subject)}
      %span.right_txt_col
        %b.crs_value
          = "$ #{product_info[product_versions[4]][price_label]}"
      %span.left_bot_col
        %b
          ATTENDANCE
        -if (product_line == 'gamsat' || product_line == 'umat')
          %p (Complete Care)
        -else
          %p (Comprehensive + Private Tutoring)
    = render "enrolments/product_version_tile_info", product_line: product_line, course: trial_course, desc: "Get the ultimate advantage with 1 on 1 in-person and online tutor support. Attendance Comprehensive + 5x 1hr private tutoring sessions."

  %li.dark_sky_down
    %a{href: dynamic_product_version_uri(product_versions[1], product_line, subject)}
      %span.right_txt_col
        %b.crs_value
          = "$ #{product_info[product_versions[1]][price_label]}"
      %span.left_bot_col
        %b
          ONLINE
        %p (Comprehensive)
    = render "enrolments/product_version_tile_info", product_line: product_line, course: trial_course, desc: "A comprehensive set of online study tools with online tutor support. Online Essentials package, plus 6 online exams, online access to tutors and 10 marked essays."
  %li.dark_green_down
    %a{href: dynamic_product_version_uri(product_versions[0], product_line, subject)}
      %span.right_txt_col
        %b.crs_value
          = "$ #{product_info[product_versions[0]][price_label]}"
      %span.left_bot_col
        %b
          ONLINE
        %p (Essentials)
    = render "enrolments/product_version_tile_info", product_line: product_line, course: trial_course, desc: "All the essentials you need to self-study online. Includes 6000+MCQs, 40 Practise Essay Topics, 1000 study guide and 22 hrs of tutorial videos."

  %li.dark_blue_down
    %a{href: dynamic_product_version_uri('custom', product_line, subject)}
      %span.right_txt_col
        %b.crs_value
          =# "$ #{product_info[product_versions[4]][price_label]}"
      %span.left_bot_col
        %b
          Custom
        %p
    = render "enrolments/product_version_tile_info", product_line: product_line, course: trial_course, desc: "Custom Course"

app/views/enrolments/_upgrade_free_trial.haml
- product_line = trial_course.product_version.type.underscore.split("_")[0]
- #product_line = "vce"
#upgrade-free-trial.text-center
  %h4
    = upgrade_free_trial_title(trial_enrolment)
  %p
    = "Enrol into one of the below courses to continue your #{product_line.upcase} preparations."
  = render 'enrolments/product_versions_summary', product_line: product_line, trial_course: trial_course

app/views/enrolments/enrol.html.haml
### This view is also not in use ######
.container
  .row
    .col-md-6
      %h1.u-text-green
        Course Details
      %dl.dl-horizontal.dl-lg
        %dt Title
        %dd= @course.name
        %dt Price
        %dd= number_to_currency @course.price
        %dt City
        %dd= @course.city
        %dt Start Date
        %dd= @course.enrolment_end_date.strftime('%Y-%m-%d')
        %dt End Date
        %dd= @course.expiry_date.strftime('%Y-%m-%d')
    .col-md-6
      %h1.u-text-green Account Details

      %dl.dl-horizontal.dl-lg
        %dt First Name
        %dd= current_user.first_name
        %dt Last Name
        %dd= current_user.last_name
        %dt Email
        %dd= current_user.email
        %dt Address
        -if current_user.address.present?
          %dd
            - if !current_user.try(:address).try(:line_one).nil?
              = current_user.address.line_one
              - if !current_user.address.line_two.nil?
                %br
                = current_user.address.line_two
            - else
              = current_user.address.try(:number)
              = current_user.address.try(:street_name)
              = current_user.address.try(:street_type)
            %br
            = current_user.address.try(:suburb)
            = current_user.address.try(:state)
            = current_user.address.try(:post_code)
          %dt Phone Number
          %dd= current_user.phone_number
        - else
        %dd N/A
  .row
    .col-md-12
      %h1.u-text-green Payment Details

      %dl.dl-horizontal.dl-lg
        %dt Price
        %dd= number_to_currency @course.price
        %dt GST (10%)
        %dd= number_to_currency @course.tax
        %dt Total Price + GST
        %dd= number_to_currency(@course.price + @course.tax)
        %span#paypal-fees{style:"display:none;"}
          %br
          %dt Paypal Fees (2%)
          %dd= number_to_currency(@course.paypal_fee)
          %dt Total + Paypal Fees
          %dd
            %strong= number_to_currency(@course.paypal_total)

      .checkbox.text-center
        %label
          =check_box_tag "check", "accept", false, id: "terms-condition-check"
          I agree to
          %a= link_to "Terms and Conditions", root_url + product_terms_uri(@course.product_version.type)
          set forth by GradReady, including, but not limited to, Course and Essay-Submission expiration dates (if applicable), and the
          %a= link_to "GradReady Refund Policy",root_url + product_faq_uri(@course.product_version.type)
  .row
    .col-md-6
      %h1.u-text-green
        %label.radio-inline
          %input{type: "radio", name: "payment-method", value: "bank"}
            Direct Debit
      #bank-pay{style:"opacity: 0.3;"}
        %h4.u-text-green Enrolment Process:
        %p
          = "Complete Direct Debit transfer AND press the I have completed payment of #{number_to_currency(@course.price + @course.tax)} button. Pressing the button will ensure that the GradReady Enrolment department receives your Enrolment request."

        %p Bank: <b>Commonwealth Bank</b>
        %p Account Name: <b> GradReady Pty Ltd. </b>
        %p BSB: <b> 06 2692 </b>
        %p Account Number: <b> 3519 6353 </b>
        %h4 Using the reference: #{@enrolment.banktrans}
        %br
        .text-center
          =link_to("I have completed payment of #{number_to_currency(@course.price + @course.tax)}",{ action: 'transfer_payment', banking_reference:@enrolment.banktrans},{method: :post,:class => 'btn btn-default disabled', id: "bank-pay-btn"})
        %br
        %p.u-standard-title.u-text-green Wait Period for Online Access:
        %p
          Up to 1 week.
        %p
          Once your payment is confirmed by the GradReady Enrolment Department, you will receive a Welcome Email and access to the Online Content. Depending on your bank, the payment may take between 3-5 working days to arrive.
        %p
          If you are undertaking an Attendance Course and the course starts in less than 2 weeks, we recommend that you use the PayPal option, for the benefit of leaving yourself enough time to go through the Online Content needed to prepare for the classes.
        %p
          For any questions regarding your Direct Debit payment, please contact
          %a.u-standard-blink{:href => "mailto:enrolments@gradready.com.au"} enrolments@gradready.com.au
    .col-md-6
      %h1.u-text-green
        %label.radio-inline
          %input{type: "radio", name: "payment-method", value: "paypal"}
            Paypal
      #paypal-pay{style:"opacity: 0.3;"}
        %h4.u-text-green Enrolment Process:
        %p
          Note that AMEX is not accepted by the Credit Card facility. However, you are able to pay via AMEX through PayPal, by clicking on the "PayPal" button below.

        %br
        .text-center
          =form_tag(course_enrolments_paypal_payment_path(@course, @enrolment))
          .form-actions
            = image_submit_tag("https://www.paypalobjects.com/en_AU/i/btn/btn_xpressCheckout.gif", id: "paypal-pay-btn", disabled: true)
        %p.u-standard-title.u-text-green Wait Period for Online Access:
        %p
          None.
          %br
          You will be redirected back to the GradReady site after payment, upon which you will have full access to the appropriate Online Content.

:javascript
  $(function(){
    update_payment_state = function() {
      paypal_enabled = function(state) {
        if (state) {
          $("#paypal-pay").fadeTo('fast', 1.0);
          $("#paypal-pay-btn").prop('disabled', false);
          $("#paypal-fees").fadeIn('fast')
        } else {
          $("#paypal-pay").fadeTo('fast', 0.3);
          $("#paypal-pay-btn").prop('disabled', true);
          $("#paypal-fees").fadeOut('fast')
        }
      }

      bank_enabled = function(state) {
        if (state) {
          $("#bank-pay").fadeTo('fast', 1.0);
          $("#bank-pay-btn").removeClass('disabled');
        } else {
          $("#bank-pay").fadeTo('fast', 0.3);
          $("#bank-pay-btn").addClass('disabled');
        }
      }


      if ($("#terms-condition-check").prop('checked')) {
        method = $("input:radio[name='payment-method']:checked").val();
        if (method == 'paypal') {
          paypal_enabled(true);
          bank_enabled(false);
        }
        if (method == 'bank') {
          paypal_enabled(false);
          bank_enabled(true);
        }

      } else {
        alert("Please agree to Terms and Conditions before proceeding.");
        paypal_enabled(false);
        bank_enabled(false);
      }
    }

    $("input:radio[name='payment-method']").change(update_payment_state)
    $("#terms-condition-check").change(update_payment_state)

  });

app/views/enrolments/new.html.haml
%h1 New Enrolment

= render 'form'

= link_to 'Back', user_enrolments_path(@student)