config/routes.rb
Rails.application.routes.draw do
  namespace :ucat do
    namespace :dashboard do
      get 'home'
    end
  end 
  resources :waitlist_users
  resources :ucat_exercises do
    collection do
      get 'welcome'
      get 'instructions'
      get 'question1'
      get 'question2'
      get 'question3'
      get 'question4'
      get 'question5'
      get 'question6'
      get 'question7'
      get 'question8'
      get 'question9'
      get 'question10'
      get 'review'
    end
  end
  resources :email_customises do
    collection do
      get 'courses'
      get 'duplicate'
    end
  end
  get '/student_enrolement_process' => 'courses#student_enrolement_process'
  get 'posts/post_unsubscribe' => 'posts#post_unsubscribe'
  post '/rate' => 'rater#create', :as => 'rate'
  put '/rate' => 'rater#update'
  resources :comments
  resources :interaction_logs
  resources :tickets do
    member do
      post 'toggle_reminder'
      post 'make_public'
      post 'make_private'
      get 'escalate_issue'
      post 'mark_complaint'
      post 'mark_for_resolved'
    end
    collection do
      get 'tags'
      delete 'destroy_old_issues'
    end
    resources :ticket_answers do
      member do
        get 'find_helpful', as: :find_helpful
        # post 'select_answer'
      end
    end
  end

  resources :user_emails, only: :index do
    collection do
      get :index_filter
    end
    post :mass_send, on: :collection
    get :download, on: :collection
    get :reset_textbook_access, on: :member
    get :update_book_access, on: :member
    delete :destroy_incomplete_transactions, on: :collection
    get :verify_transactions, on: :collection
  end
  get 'textbook_deliveries', to: 'user_emails#textbook_deliveries'
  get 'errors/not_found'
  get 'errors/internal_server_error'

  resources :tutor_schedules
  resources :purchase_addons do
    collection do
      post 'paypal_payment' => 'purchase_addons#paypal_payment'
    end
  end

  resources :diagnostic_test_attempts, except: [:edit, :update] do
    resources :section_attempts, only: [:index, :show] do
      resources :section_item_attempts, only: :index do
        collection do
          put 'complete'
          get 'review'
          put 'update_answer'
        end
        member do
          get :exam_review_videos
          get :exam_review_textbooks
          get :exam_feedback
        end
      end
    end
  end


  resources :shippings do
    collection do
      post 'update_out_of_stock'
    end
  end

  resources :textbook_deliveries do
    collection do
      post 'create_or_update_textbook'
    end
  end

  resources :course_recommender_usages do
    collection do
      get 'tracking'
    end
  end

  resources :online_mock_exam_attempts, except: [:edit, :update] do
    member do
      get :download
    end
    collection do
      get :refresh_document
    end
    resources :section_attempts, only: [:index, :show] do
      resources :section_item_attempts, only: :index do
        collection do
          put 'complete'
          get 'review'
          put 'update_answer'
        end
        member do
          get :exam_review_videos
          get :exam_review_textbooks
          get :exam_feedback
          get :mcq_exam_question_rating
          post :create_update_question_rating
        end
      end
    end
  end

  resources :online_mock_exam_attempt_temps, except: [:edit, :update] do
    member do
      get :download
    end
    collection do
      get :refresh_document
    end
    resources :section_attempts, only: [:index, :show] do
      resources :section_item_attempts, only: :index do
        collection do
          put 'complete'
          get 'review'
          put 'update_answer'
        end
        member do
          get :exam_review_videos
          get :exam_review_textbooks
          get :exam_feedback
          get :mcq_exam_question_rating
          post :create_update_question_rating
        end
      end
    end
  end

  resources :online_exam_attempts, except: [:edit, :update] do
    collection do
      post 'create_print_exam'
    end
    member do
      get 'print_exam_questions'
      get :print_count
    end
    resources :section_attempts, only: [:index, :show] do
      resources :section_item_attempts, only: :index do
        collection do
          put 'complete'
          get 'review'
          put 'update_answer'
        end
        member do
          get :exam_review_videos
          get :exam_review_textbooks
          get :exam_feedback
          get :mcq_exam_question_rating
          post :create_update_question_rating
        end
      end
    end
  end

  resources :online_mock_exams do
    collection do
      get :archived_online_mock_exams
    end
  end
  resources :online_exams do
    member do
      get :download
      get :change_show_stat
      put :change_lock
      post :duplicate
    end
    resources :sections do
      resources :section_items do
        member do
          delete :remove_question
        end
      end
    end
    collection do
      get :check_position
      get :archived_online_exams
      post :update_product_line_positions
    end
  end

  resources :diagnostic_tests do
    member do
      get :change_show_stat
      put :change_lock
    end
    resources :sections do
      resources :section_items do
        member do
          delete :remove_question
        end
      end
    end
  end

  get 'discount/index'
  get "/exercises/:exercise_id/mcq_attempts/review" => "exercise_review#review", as: :review_exercise_exercise_review
  delete 'exercises/:exercise_id/return_to_mcq' => 'exercise_mcqs#return_to_mcq', as: :return_to_mcq
  post 'exercises/:id/repeat' => 'exercise_mcqs#repeat', as: :repeat
  post 'exercises/review_questions' => 'exercise_mcqs#review_questions', as: :review_questions
  resources :exercises do
    resources :exercise_review, except: [:new, :edit, :create, :edit, :update, :destroy] do
      member do
        get :exercise_review_videos
        get :exercise_review_textbooks
        get :give_feedback
        get :mcq_exam_question_rating
        post :create_update_question_rating
      end
    end
    resources :mcq_attempts, except: [:new, :edit, :create,
            :edit, :update, :destroy] do
      collection do
        put 'update_answer'
        put 'update_mcq_answer'
      end
    end
  end

  resources :job_application_forms, :path => 'jobs' do
    resources :job_applications, :path => 'job-applications' do
      get 'download_all', on: :collection
      get 'get_tag_childrens', on: :collection
      get 'download', on: :member
    end

    get 'archived_jobs', on: :collection
    get 'available-positions', to: 'job_application_forms#available_positions', on: :collection

    get 'show_available_position', on: :member
  end
  resources :job_applications, :path => 'job-applications', only: [] do
    get 'search_applications', on: :collection
    post 'update_interview_date', on: :collection
  end

  # resources :features
  resources :master_features do
    post :master_feature_tags, on: :collection
  end
  # get 'enrolment/:id/' => 'enrolments#show'
  resources :enrolments, only: [:show] do
    member do
      get :student_addon_enrolment
      get :transfer_by
      patch :unenrol_or_renrol
    end
    collection do
      put :attach_enrolment_details
    end
  end

  resources :common_contents, except: [:show, :index]
  resources :free_study_buddies
  resources :study_buddies
  resources :countdown_timers
  resources :download_hit_counters, only: [:index, :edit, :update]
  get 'courses/public_course_cities' => 'courses_filter#public_course_cities'
  get 'courses/filtered_product_versions' => 'courses_filter#filtered_product_versions'
  get 'courses/filtered_transfer_courses' => 'courses_filter#filtered_transfer_courses'

  get 'courses/list_cities' => 'courses_filter#list_cities'
  get 'courses/list_course_lessons' => 'courses_filter#list_course_lessons'
  get 'courses/list_courses_by_city' => 'courses_filter#list_courses_by_city'
  resources :courses do
    get 'enrolments/enrol' => 'enrolments#enrol'
    get 'enrolments/discount_course_enrolment'=> 'enrolments#discount_course_enrolment'
    get 'enrolments/quick_enrol' => 'enrolments#quick_enrol'
    get 'enrolments/student_course_enrolment' => 'enrolments#student_course_enrolment'
    post 'enrolments/paypal_payment' => 'enrolments#paypal_payment'
    post 'enrolments/transfer_payment' => 'enrolments#transfer_payment'
    get 'enrolments/cancel' => 'enrolments#cancel'
    get 'enrolments/transfer_course' => 'enrolments#transfer_course'
    get 'enrolments/custom_enrol' => 'enrolments#custom_enrol'
    
    get :trial_enabled, on: :member
    collection do
      post :set_current_course
      get :archived_courses
      get :get_course_type
    end
    member do
      post :duplicate
      post :unarchived
      get :update_course_id
      get :get_addons
    end
  end
  
  resources :transfer_transactions do
    collection do
      get '/transfer_transaction' => 'transfer_transaction#show'
    end
  end

  get '/users/view_as/:user_id' => 'users#become', as: :view_as
  resources :users, except: [:show, :index] do
    collection do
      get :check_email
      get :check_username
      get :reset_ol_exam
      get :reset_diganostic
      get :reset_essay
      get :reset_mock_exam
      delete :destroy_all
      delete :destroy_ongoing_orders
      get :verify_users
      get :cancel_appointment
      post :study_guide
      post :free_gamsat_trial
      get :reset_online_mock_exam_attempt
      get :display_expiry_date
    end
    resources :enrolments, except: [:index, :show] do
    end
    member do
      get :transfer_data
      put :deactivate
      put :resend_invitation
      get :reset_exams
      get :update_contact
      put :save_detail
      get :course_details
      post :transfer
      get :tutor_interaction_logs
    end
    post :generate_new_password_email

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  layout 'layouts/dashboard'
  before_action :authenticate_user!, except: [:answerer_for_tag, :children_for_tag, :root_tags, :ticket_tags]
  before_action :ensure_access_allowed!, except: [:answerer_for_tag, :children_for_tag, :root_tags, :mcq_stem_review_videos, :ticket_tags]
  before_action :set_tag, only: [:show, :edit, :update, :destroy, :answerer_for_tag, :children_for_tag]

  respond_to :html, :js

  def index
    @tags = policy_scope(Tag)
    @filterrific = initialize_filterrific(
        @tags,
        params[:filterrific],
        select_options: {
          by_product_line: ['Gamsat', 'Umat', 'Vce', 'Hsc']
        }
    ) or return
    @tags = @filterrific.find
  end

  def children_for_tag
    #   Returns the root tags available to the user
    @tags = @tag.children
    render template: "tags/index", formats: [:json]
  end
  def children_for_tags
    tags = policy_scope(Tag).select { |tag| tag.parent_id == params[:tag_id].to_i && tag.is_public == true }
    render json: tags
  end

  def destroy
    @tag.destroy
    respond_with(@tag)
  end

  def new
    @tag = Tag.new
    authorize @tag
    respond_with(@tag)
  end

  def edit
  end

  def show
    respond_with(@tag)
  
  end

  def create
    @tag = Tag.new(tag_params)
    authorize @tag
    respond_to do |format|
      if @tag.save
        format.html { redirect_to tags_path, notice: 'Tag successfully created' }
        format.json { render :index, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
        flash[:error] = 'Please review the problems below.'
      end
    end
  end
  def search
    @tags = Tag.search_descendant_tags(params[:search])
    @return_path = params[:return_path]
  end
  def answerer_for_tag
  end

  def update
    @tag.update(tag_params)
    respond_to do |format|
      format.html { redirect_to tags_path, notice: 'Tag was successfully updated. ' }
      format.json { render :index, status: :ok, location: @tag }
    end
  end

  def root_tags
    @tags = current_root_tags
    render template: "tags/index", formats: [:json]
  end

  def ticket_tags
    @tags = current_ticket_tags
    render template: "tags/index", formats: [:json]
  end

  def mcq_stem_review_videos
    @tag = Tag.find(params[:id])
    @videos = Vod.by_tags(@tag)
    respond_to do |format|
      format.js
    end
  end


  private
  
  def current_ticket_tags
    return @current_root_tags if @current_root_tags
    @ticket_tags = policy_scope(Tag)
    if current_user && current_user.student?
      @ticket_tags = @ticket_tags
    else
      @ticket_tags = @ticket_tags.where(is_public: true).order(:name)
    end

    all_tags = @ticket_tags.includes(:parent).to_a
    @current_root_tags = all_tags.select { |tag| tag.parent_id.nil? || !all_tags.include?(tag.parent) }
  end

  def current_root_tags
    return @current_root_tags if @current_root_tags
    all_tags = policy_scope(Tag).includes(:parent).to_a
    @current_root_tags = all_tags.select { |tag| tag.parent_id.nil? || !all_tags.include?(tag.parent) }
  end

  def ensure_access_allowed!
    user_not_authorized unless [:tutor, :manager, :admin, :superadmin].include? current_user.try(:role).try(:to_sym) unless current_user.present? && current_user.student?
  end

  def set_tag
    @tag = Tag.find_by(id: params[:id])
    authorize @tag
  end

  def tag_params
    params.require(:tag).permit(:name, :description, :tagging_count, :parent_id, :is_public, :instruction)
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.haml
= simple_form_for(@tag) do |f|
  = f.error_notification
  .form-inputs
    = f.input :name
    = f.input :description
    = f.input :instruction, as: :ckeditor, input_html: { ckeditor: { height: 200 }}
    = f.input :is_public
    = f.input :parent_id, collection: Tag.order(:name).reject { |tag| tag == @tag }, as: :select, label_method: :name  ,input_html: {class: 'chosen-select'}
  .form-actions
    = f.button :submit, "Create Tag"

app/views/tags/_index.html.haml
#filterrific_results
  %table.gr-table.gr-table-bordered.table-hover
    %thead
      %tr
        %th Name
        %th Parent
        %th{ colspan: '2' } Actions
    %tbody
      - @tags.each do |tag|
        %tr
          %td= tag.name
          %td= tag.parent.name if tag.parent
          %td= link_to 'Edit', edit_tag_path(tag), class: 'btn btn-info btn-sm'
          -if current_user.superadmin? || current_user.admin?
            -if tag.taggings.count == 0
              %td= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'

  - if !current_user.student?
    %h3 Tree view
    - Tag.walk_tree do |tag, level|
      - if level==0
        = link_to "#{tag.name}", "javascript:void(0)"
        %br
      - elsif level == 1
        = link_to "|_ #{tag.name}", "javascript:void(0)"
        %br
      - else
        = link_to "#{'__' * level} |_ #{tag.name}", "javascript:void(0)"
        %br

app/views/tags/_list_tag.html.haml
.nested-tag
  %p
    #tag-field
      = check_box_tag(attribute, tag.id, checked: true)
      = tag.name

:javascript
  $(document).ready( function () {
    $("input[type=checkbox]").on('change', function() {
        $(this).closest("#tag-field").hide();
    });
  });

app/views/tags/_mcq_stem_videos_modal.html.haml
#mcq_stem-vid-modal.modal.fade{:role => "dialog", :tabindex => "-1", }
  .modal-dialog.modal-md{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h4.modal-title Videos
      .modal-body
        - if vods.present?
          - vods.first(3).each do |vod|
            .li.text-align-left
              = link_to "#{vod.title}", vod_path(vod)
            %br/
        -else
          No video present.
      .modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close

app/views/tags/edit.html.haml
%h1 Editing tag
= render 'form'
%br
= link_to 'Back', tags_path, class: 'btn btn-danger'

app/views/tags/index.html.haml
%h1 Listing tags
.panel.panel-default
  .panel-body
    = form_for_filterrific @filterrific do |f|
      .form-group
        %label Type
        =f.select(:by_product_line, @filterrific.select_options[:by_product_line],{ include_blank: 'All' }, class: 'form-control')
      = link_to 'Reset filters', reset_filterrific_url, class: 'btn btn-default'

- unless current_user.student?
  = link_to 'New Tag', new_tag_path, class: 'btn btn-gradready green'
%br
%br

=render(partial: 'tags/index', locals: { tags: @tags })

app/views/tags/index.js.erb
<% js = escape_javascript(
  render(partial: 'tags/index', locals: { tags: @tags })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/tags/mcq_stem_review_videos.js.erb
$("#mod_mcq_attempt").html("<%=escape_javascript(render('mcq_stem_videos_modal', vods: @videos))%>");
$("#mcq_stem-vid-modal").modal("show");

app/views/tags/new.html.haml
%h1 New Tag
= render 'form'
= link_to 'Back', tags_path

app/views/tags/search.js.erb
$("#results").html("<%= escape_javascript(render(partial: "#{@return_path}/tag_search", locals: { tags: @tags } )) %>");