config/routes.rb
Rails.application.routes.draw do
  namespace :ucat do
    namespace :dashboard do
      get 'home'
    end
  end 
  resources :waitlist_users
  resources :ucat_exercises do
    collection do
      get 'welcome'
      get 'instructions'
      get 'question1'
      get 'question2'
      get 'question3'
      get 'question4'
      get 'question5'
      get 'question6'
      get 'question7'
      get 'question8'
      get 'question9'
      get 'question10'
      get 'review'
    end
  end
  resources :email_customises do
    collection do
      get 'courses'
      get 'duplicate'
    end
  end
  get '/student_enrolement_process' => 'courses#student_enrolement_process'
  get 'posts/post_unsubscribe' => 'posts#post_unsubscribe'
  post '/rate' => 'rater#create', :as => 'rate'
  put '/rate' => 'rater#update'
  resources :comments
  resources :interaction_logs
  resources :tickets do
    member do
      post 'toggle_reminder'
      post 'make_public'
      post 'make_private'
      get 'escalate_issue'
      post 'mark_complaint'
      post 'mark_for_resolved'
    end
    collection do
      get 'tags'
      delete 'destroy_old_issues'
    end
    resources :ticket_answers do
      member do
        get 'find_helpful', as: :find_helpful
        # post 'select_answer'
      end
    end
  end

  resources :user_emails, only: :index do
    collection do
      get :index_filter
    end
    post :mass_send, on: :collection
    get :download, on: :collection
    get :reset_textbook_access, on: :member
    get :update_book_access, on: :member
    delete :destroy_incomplete_transactions, on: :collection
    get :verify_transactions, on: :collection
  end
  get 'textbook_deliveries', to: 'user_emails#textbook_deliveries'
  get 'errors/not_found'
  get 'errors/internal_server_error'

  resources :tutor_schedules
  resources :purchase_addons do
    collection do
      post 'paypal_payment' => 'purchase_addons#paypal_payment'
    end
  end

  resources :diagnostic_test_attempts, except: [:edit, :update] do
    resources :section_attempts, only: [:index, :show] do
      resources :section_item_attempts, only: :index do
        collection do
          put 'complete'
          get 'review'
          put 'update_answer'
        end
        member do
          get :exam_review_videos
          get :exam_review_textbooks
          get :exam_feedback
        end
      end
    end
  end


  resources :shippings do
    collection do
      post 'update_out_of_stock'
    end
  end

  resources :textbook_deliveries do
    collection do
      post 'create_or_update_textbook'
    end
  end

  resources :course_recommender_usages do
    collection do
      get 'tracking'
    end
  end

  resources :online_mock_exam_attempts, except: [:edit, :update] do
    member do
      get :download
    end
    collection do
      get :refresh_document
    end
    resources :section_attempts, only: [:index, :show] do
      resources :section_item_attempts, only: :index do
        collection do
          put 'complete'
          get 'review'
          put 'update_answer'
        end
        member do
          get :exam_review_videos
          get :exam_review_textbooks
          get :exam_feedback
          get :mcq_exam_question_rating
          post :create_update_question_rating
        end
      end
    end
  end

  resources :online_mock_exam_attempt_temps, except: [:edit, :update] do
    member do
      get :download
    end
    collection do
      get :refresh_document
    end
    resources :section_attempts, only: [:index, :show] do
      resources :section_item_attempts, only: :index do
        collection do
          put 'complete'
          get 'review'
          put 'update_answer'
        end
        member do
          get :exam_review_videos
          get :exam_review_textbooks
          get :exam_feedback
          get :mcq_exam_question_rating
          post :create_update_question_rating
        end
      end
    end
  end

  resources :online_exam_attempts, except: [:edit, :update] do
    collection do
      post 'create_print_exam'
    end
    member do
      get 'print_exam_questions'
      get :print_count
    end
    resources :section_attempts, only: [:index, :show] do
      resources :section_item_attempts, only: :index do
        collection do
          put 'complete'
          get 'review'
          put 'update_answer'
        end
        member do
          get :exam_review_videos
          get :exam_review_textbooks
          get :exam_feedback
          get :mcq_exam_question_rating
          post :create_update_question_rating
        end
      end
    end
  end

  resources :online_mock_exams do
    collection do
      get :archived_online_mock_exams
    end
  end
  resources :online_exams do
    member do
      get :download
      get :change_show_stat
      put :change_lock
      post :duplicate
    end
    resources :sections do
      resources :section_items do
        member do
          delete :remove_question
        end
      end
    end
    collection do
      get :check_position
      get :archived_online_exams
      post :update_product_line_positions
    end
  end

  resources :diagnostic_tests do
    member do
      get :change_show_stat
      put :change_lock
    end
    resources :sections do
      resources :section_items do
        member do
          delete :remove_question
        end
      end
    end
  end

  get 'discount/index'
  get "/exercises/:exercise_id/mcq_attempts/review" => "exercise_review#review", as: :review_exercise_exercise_review
  delete 'exercises/:exercise_id/return_to_mcq' => 'exercise_mcqs#return_to_mcq', as: :return_to_mcq
  post 'exercises/:id/repeat' => 'exercise_mcqs#repeat', as: :repeat
  post 'exercises/review_questions' => 'exercise_mcqs#review_questions', as: :review_questions
  resources :exercises do
    resources :exercise_review, except: [:new, :edit, :create, :edit, :update, :destroy] do
      member do
        get :exercise_review_videos
        get :exercise_review_textbooks
        get :give_feedback
        get :mcq_exam_question_rating
        post :create_update_question_rating
      end
    end
    resources :mcq_attempts, except: [:new, :edit, :create,
            :edit, :update, :destroy] do
      collection do
        put 'update_answer'
        put 'update_mcq_answer'
      end
    end
  end

  resources :job_application_forms, :path => 'jobs' do
    resources :job_applications, :path => 'job-applications' do
      get 'download_all', on: :collection
      get 'get_tag_childrens', on: :collection
      get 'download', on: :member
    end

    get 'archived_jobs', on: :collection
    get 'available-positions', to: 'job_application_forms#available_positions', on: :collection

    get 'show_available_position', on: :member
  end
  resources :job_applications, :path => 'job-applications', only: [] do
    get 'search_applications', on: :collection
    post 'update_interview_date', on: :collection
  end

  # resources :features
  resources :master_features do
    post :master_feature_tags, on: :collection
  end
  # get 'enrolment/:id/' => 'enrolments#show'
  resources :enrolments, only: [:show] do
    member do
      get :student_addon_enrolment
      get :transfer_by
      patch :unenrol_or_renrol
    end
    collection do
      put :attach_enrolment_details
    end
  end

  resources :common_contents, except: [:show, :index]
  resources :free_study_buddies
  resources :study_buddies
  resources :countdown_timers
  resources :download_hit_counters, only: [:index, :edit, :update]
  get 'courses/public_course_cities' => 'courses_filter#public_course_cities'
  get 'courses/filtered_product_versions' => 'courses_filter#filtered_product_versions'
  get 'courses/filtered_transfer_courses' => 'courses_filter#filtered_transfer_courses'

  get 'courses/list_cities' => 'courses_filter#list_cities'
  get 'courses/list_course_lessons' => 'courses_filter#list_course_lessons'
  get 'courses/list_courses_by_city' => 'courses_filter#list_courses_by_city'
  resources :courses do
    get 'enrolments/enrol' => 'enrolments#enrol'
    get 'enrolments/discount_course_enrolment'=> 'enrolments#discount_course_enrolment'
    get 'enrolments/quick_enrol' => 'enrolments#quick_enrol'
    get 'enrolments/student_course_enrolment' => 'enrolments#student_course_enrolment'
    post 'enrolments/paypal_payment' => 'enrolments#paypal_payment'
    post 'enrolments/transfer_payment' => 'enrolments#transfer_payment'
    get 'enrolments/cancel' => 'enrolments#cancel'
    get 'enrolments/transfer_course' => 'enrolments#transfer_course'
    get 'enrolments/custom_enrol' => 'enrolments#custom_enrol'
    
    get :trial_enabled, on: :member
    collection do
      post :set_current_course
      get :archived_courses
      get :get_course_type
    end
    member do
      post :duplicate
      post :unarchived
      get :update_course_id
      get :get_addons
    end
  end
  
  resources :transfer_transactions do
    collection do
      get '/transfer_transaction' => 'transfer_transaction#show'
    end
  end

  get '/users/view_as/:user_id' => 'users#become', as: :view_as
  resources :users, except: [:show, :index] do
    collection do
      get :check_email
      get :check_username
      get :reset_ol_exam
      get :reset_diganostic
      get :reset_essay
      get :reset_mock_exam
      delete :destroy_all
      delete :destroy_ongoing_orders
      get :verify_users
      get :cancel_appointment
      post :study_guide
      post :free_gamsat_trial
      get :reset_online_mock_exam_attempt
      get :display_expiry_date
    end
    resources :enrolments, except: [:index, :show] do
    end
    member do
      get :transfer_data
      put :deactivate
      put :resend_invitation
      get :reset_exams
      get :update_contact
      put :save_detail
      get :course_details
      post :transfer
      get :tutor_interaction_logs
    end
    post :generate_new_password_email

app/controllers/ucat/dashboard_controller.rb
class Ucat::DashboardController < ApplicationController
  before_action :authenticate_user!
  layout 'ucat_dashboard'

  def home
    @only_dd_pending = false
    @only_expired_course = false
    if current_user.student? && !current_user.paid_courses.present? && (current_user.orders.where(status: :ongoing).present? && current_user.orders.where(status: :ongoing).last.purchase_items.present?) && AdminControl.find_by(name: 'Signup view').try(:new_view)
      if  current_user.payment_flow_step.present? && request.path != current_user.payment_flow_step
        redirect_to current_user.payment_flow_step
      else
        current_user.orders.where(status: :ongoing).last
      end
    elsif current_user.student? && !current_user.confirmed?
      render layout: 'layouts/student_page'
    elsif current_user.student? && !current_user.questionnaire.present? && (current_user.paid_courses.present? || current_user.orders.pending.present?) && (!current_user.has_free_trial_only? || params[:update_background])
      if (current_user.active_course.present? && current_user.active_course.customable? && !current_user.address.present?)
        redirect_to current_user.payment_flow_step
      else
        @update_background = true
        @user = current_user
        @user.build_questionnaire
        render layout: 'layouts/student_page'
      end
    elsif !current_user.paid_courses.present? && current_user.orders.pending.present?
      @only_dd_pending = true
      render layout: 'layouts/student_page'
    elsif (current_user.paid_enrolments.count == 1) && ((current_user.paid_enrolments.first.trial? && current_user.paid_enrolments.first.trial_expired?) || current_user.paid_enrolments.first.course.expired?)
      @only_expired_course = true
    else
      @update_background = false
      @announcement = get_dashboard_announcement
      @user_announcement = current_user.user_announcements.find_by(announcement_id: @announcement.id) if @announcement.present?
      @last_order = current_user.orders.where(status: Order.statuses[:paid]).last
    end
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def feature_hash(feature_name)
    ## TODO: This needs to be updated to be dynamic from the models/features folder
    features = {
      'Mcq' => {
        url: "exercises_path",
        icon: "fa fa-plus-square",
        title: "MCQs"
      },
      'McqStem' => {
        url: "exercises_path",
        icon: "fa fa-plus-square",
        title: "MCQs"
      },
      'Vod' => {
        url: "dashboard_vods_path",
        icon: "fa fa-video-camera",
        title: "Videos"
      },
      'Essay' => {
        url: "essays_path",
        icon: "fa fa-pencil",
        title: "Essays"
      },
      'Exam' => {
        url: "exams_path",
        icon: "fa fa-tag",
        title: "Exams"
        },
      'Textbook' => {
            url: 'dashboard_textbooks_path',
            icon: 'fa fa-book',
            title: 'Textbooks'
      },
      'Book Tutor' => {
        url: 'dashboard_book_tutor_path',
        icon: 'fa fa-calendar-plus-o',
        title: 'Book Tutor'
      }
    }
    features[feature_name]
  end

  def appointment_locations(appointments)
    appointments.map(&:location).reject(&:blank?).uniq.join(', ')
  end

  def tab_collection
    [
      ["Reasoning Textbook(Online TB) DL - No", "/dashboard/textbooks?type=additional_chapters"],
      ["Foundation Textbook(Online or Hardcopy TB) DL - No", "/dashboard/textbooks?type=textbook_chapters"],
      ["Textbook Slides(Online or Hardcopy TB) DL - No", "/dashboard/textbooks?type=textbook_slides"],
      ["PBL Additional Resources (PBLs) DL - Yes", "/dashboard/textbooks?type=attendance_course_resources"],
      ["PBL In-Class Slides (PBLs) DL - No",'/dashboard/textbooks?type=attendance_course_slides'],
      ["Revision Weekend (Revision Weekend) DL - No", "/dashboard/textbooks?type=revision_weekend"],
      ["Mock Exam (Online Exams) DL - No", "/dashboard/textbooks?type=mock_exam"],
      ["Supplementary Resources (All paying and non-paying students) DL - No", "/dashboard/textbooks?type=supplementary_resources"],
      ["Downloadable Resources (All paying and non-paying students) DL - Yes", "/dashboard/textbooks?type=downloadable_resources"]
    ]
  end

  def select_tab_values(type)
    case type 
      when 'attendance_course_resources'
        "/dashboard/textbooks?type=attendance_course_resources"
      when 'attendance_course_slides'
        '/dashboard/textbooks?type=attendance_course_slides'
      when'textbook_chapters'
        '/dashboard/textbooks?type=textbook_chapters'
      when 'additional_chapters'
        '/dashboard/textbooks?type=additional_chapters'
      when 'revision_weekend'
        '/dashboard/textbooks?type=revision_weekend'
      when 'mock_exam'
        '/dashboard/textbooks?type=mock_exam'
      when 'textbook_slides'
        '/dashboard/textbooks?type=textbook_slides'
      when 'supplementary_resources'
        '/dashboard/textbooks?type=supplementary_resources'
      when 'downloadable_resources'
        '/dashboard/textbooks?type=downloadable_resources'
      else 
        '/dashboard/textbooks(type: additional_chapters)'
    end

  end

  def appointment_view_selections
    if current_user.manager? || current_user.admin? || current_user.superadmin?
      [["PT Sessions by Tutor - Session Sum"], ["PT Sessions by Tutor - Student Breakdown" ], ["PT Sessions by Student - Unused Sessions"]]
    elsif current_user.tutor?
      [["Log Hours"], ["PT Sessions by Tutor - Student Breakdown"]]
    end
  end

  def appointment_view_selections_default
    if current_user.manager? || current_user.admin? || current_user.superadmin?
      "PT Sessions by Tutor - Session Sum"
    else
      "Log Hours"
    end
  end

  def display_args(selection)
    all_args = {
      "PT Sessions by Tutor - Session Sum" => { partial: 'dashboard/tutor_appointments',
                                                locals: { appointments: @appointments, tutors: @tutors, availablities: @availablities } },
      "PT Sessions by Tutor - Student Breakdown" => { partial: 'dashboard/student_tutor_appointment' },
      "PT Sessions by Student - Unused Sessions" => { partial: 'dashboard/unbooked_student_tutor_appointment' },
      "Log Hours" => { partial: 'tutor_availabilities/booked_appointments',
                       locals: { booked_appointments: current_user.tutor_profile.tutor_appointments.active.where(course_id: @courses.ids) } }
    }

    selection = appointment_view_selections_default if selection.blank?
    all_args[selection]
  end

  def default_date 
    date_to_display = @filterrific.with_end_filter.try(:to_date)
    date_to_display = (date_to_display + 2) if date_to_display == Date.today
    return date_to_display
  end

  def get_textbook(textbook)
    return textbook.textbook_reads.find_by(user_id: current_user.id)
  end

end

app/views/dashboard/online_exams/index.html.haml
.alert.alert-warning.alert-dismissible{:role => "alert"}
  %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
    %span{"aria-hidden" => "true"} ×
  - if current_user && (current_user.student?)
    - if !@announcement.nil?
      = render 'announcements/student_announcement', announcement: @announcement, title: 'Online exams Announcements', user_announcement: @user_announcement

.panel.panel-warning
  .panel-heading
    %h1.panel-title
      %strong Online exams
  .panel-body
    - if @exams.present?
      .table-responsive
        %table.table.table-bordered.table-hover
          %thead
            %tr
              %th Title
              %th Num sections
              %th Status
              %th Actions
          %tbody
            - @exams.each do |e|
              %tr{'data-link': url_for(dashboard_online_exam_path(e))}
                %td
                  %i.fa.fa-arrow-right
                  = e.title
                %td
                  - if e.exam_sections.present?
                    = e.exam_sections.size
                  - else
                    %i No exam sections.
                %td
                  - if e.date_finished.present?
                    %span.label.label-danger Completed
                  - elsif e.date_started.present?
                    %span.label.label-warning Started
                  - else
                    %span.label.label-info New
                %td= link_to 'Delete', dashboard_online_exam_path(e), class: 'btn btn-danger btn-sm cl-white', method: :delete, :data => { :confirm => 'Are you sure?' }

    - else
      %i There are not any online exams.

app/views/dashboard/online_exams/mcqs.html.haml
-# .container
-#   .row
-#     = simple_form_for :mcqs, url: dashboard_online_exam_mcqs_path, method: :get do |i|
-#       .panel.panel-default
-#         #mcq_stem=
-#           .panel-body
-#             .col-md-10.col-md-offset-1
-#               #timer.pull-right.btn.btn-success
-#                 Time:
-#                 %span#minutes
-#                 %span :
-#                 %span#seconds
-#               %h2
-#                 %strong= @mcq_stem.title.html_safe
-#               = @mcq_stem.description.html_safe
-#               - @mcq_stem.mcqs.each do |mcq|
-#                 = mcq.question.html_safe
-#                 = i.simple_fields_for :answers, index: mcq.id do |f|
-#                   =f.hidden_field :time_taken, id: "secondsTimer"
-#                   -# =f.input :user_id, as: :hidden, input_html: { value: current_user.id }
-#                   =f.input :time_started, as: :hidden, input_html: { value: DateTime.now }
-#                   =f.collection_radio_buttons :mcq_answer_id, mcq.mcq_answers, :id, :answer, label: false, item_label_class: 'radio mg-left'
-#
-#           .panel-footer
-#             .btn-group
-#               =i.button :submit, "Submit answers", class: 'btn btn-default'

.container
  .row
    = simple_form_for :mcqs, url: dashboard_online_exam_save_exam_section_path(exam_id: @exam.id) do |i|
      .panel.panel-default
        #mcq_stem
          .panel-body
            .col-md-10.col-md-offset-1
              #timer.pull-right.btn.btn-success
                Time:
                %span#minutes
                %span :
                %span#seconds
              %h2
                %strong= @exam_section.title.html_safe
              -# = @exam_section.description.html_safe
              
              - @exam_section.mcqs.each do |mcq|
                = mcq.question.html_safe
                = i.simple_fields_for :answers, index: mcq.id do |f|
                  =f.hidden_field :time_taken, id: "secondsTimer"
                  =f.input :time_started, as: :hidden, input_html: { value: DateTime.now }
                  =f.collection_radio_buttons :mcq_answer_id, mcq.mcq_answers, :id, :answer, label: false, item_label_class: 'radio mg-left'

          .panel-footer
            .btn-group
              =i.button :submit, "Submit answers", class: 'btn btn-default'

:javascript
  var pad, sec, secT;
  sec = 120;
  secT = 0;
  pad = function(val) {
    if (val > 9) {
      return val;
    } else {
      return '0' + val;
    }
  };
  setInterval((function() {
    $('#seconds').html(pad(--sec % 60));
    $('#minutes').html(pad(parseInt(sec / 60, 10)));
    $('#secondsTimer').val(pad(++secT));
    if (sec === 0) {
      console.log('end time');
    }
  }), 1000);

app/views/dashboard/online_exams/show.html.haml
.container
  .row
    .panel.panel-warning
      .panel-heading
        %h1.panel-title
          %strong= @exam.title
      .panel-body
        - if @exam_sections.present?
          - if @exam.date_finished.present?
            .col-md-10.col-md-offset-1.mg-top
              .panel.panel-success
                .panel-heading
                  %h1.panel-title
                    %strong Exam sections:
                .panel-body
                .table-responsive
                  %table.table.table-bordered.table-hover
                    %thead
                      %tr
                        %th Title
                        %th Num questions
                        %th Difficulty
                        %th Duration
                        %th Status
                    %tbody
                      - @exam_sections.each do |es|
                        %tr
                          %td= es.title
                          %td
                            - if es.mcqs.present?
                              = es.mcqs.size
                            - else
                              %i No mcqs.
                          %td= es.dificultyRating
                          %td Duration
                          %td Status
              = render 'dashboard/partial/correctness_list'

          - else
            .panel.panel-success
              .panel-heading
                %h1.panel-title
                  %strong Exam sections:
              .panel-body
              .table-responsive
                %table.table.table-bordered.table-hover
                  %thead
                    %tr
                      %th Title
                      %th Num questions
                      %th Difficulty
                      %th Duration
                      %th Status
                  %tbody
                    - @exam_sections.each do |es|
                      %tr
                        %td= es.title
                        %td
                          - if es.mcqs.present?
                            = es.mcqs.size
                          - else
                            %i No mcqs.
                        %td= es.dificultyRating
                        %td Duration
                        %td Status
        - else
          There are not any exam sections.
      .panel-footer
        .btn-group
          = link_to 'Back', dashboard_online_exams_path, class: 'btn btn-default'
          - if @exam.date_finished.blank?
            = link_to 'Start', dashboard_online_exam_mcqs_path(online_exam_id: @exam.id, id: @exam.slug), class: 'btn btn-danger cl-white', :data => { :confirm => 'Are you sure?' }
          - if @exam.date_finished.present?
            = link_to 'Review', '', class: 'btn btn-warning cl-white'