config/routes.rb
Rails.application.routes.draw do
  namespace :ucat do
    namespace :dashboard do
      get 'home'
    end
  end 
  resources :waitlist_users
  resources :ucat_exercises do
    collection do
      get 'welcome'
      get 'instructions'
      get 'question1'
      get 'question2'
      get 'question3'
      get 'question4'
      get 'question5'
      get 'question6'
      get 'question7'
      get 'question8'
      get 'question9'
      get 'question10'
      get 'review'
    end
  end
  resources :email_customises do
    collection do
      get 'courses'
      get 'duplicate'
    end
  end
  get '/student_enrolement_process' => 'courses#student_enrolement_process'
  get 'posts/post_unsubscribe' => 'posts#post_unsubscribe'
  post '/rate' => 'rater#create', :as => 'rate'
  put '/rate' => 'rater#update'
  resources :comments
  resources :interaction_logs
  resources :tickets do
    member do
      post 'toggle_reminder'
      post 'make_public'
      post 'make_private'
      get 'escalate_issue'
      post 'mark_complaint'
      post 'mark_for_resolved'
    end
    collection do
      get 'tags'
      delete 'destroy_old_issues'
    end
    resources :ticket_answers do
      member do
        get 'find_helpful', as: :find_helpful
        # post 'select_answer'
      end
    end
  end

  resources :user_emails, only: :index do
    collection do
      get :index_filter
    end
    post :mass_send, on: :collection
    get :download, on: :collection
    get :reset_textbook_access, on: :member
    get :update_book_access, on: :member
    delete :destroy_incomplete_transactions, on: :collection
    get :verify_transactions, on: :collection
  end
  get 'textbook_deliveries', to: 'user_emails#textbook_deliveries'
  get 'errors/not_found'
  get 'errors/internal_server_error'

  resources :tutor_schedules
  resources :purchase_addons do
    collection do
      post 'paypal_payment' => 'purchase_addons#paypal_payment'
    end
  end

  resources :diagnostic_test_attempts, except: [:edit, :update] do
    resources :section_attempts, only: [:index, :show] do
      resources :section_item_attempts, only: :index do
        collection do
          put 'complete'
          get 'review'
          put 'update_answer'
        end
        member do
          get :exam_review_videos
          get :exam_review_textbooks
          get :exam_feedback
        end
      end
    end
  end


  resources :shippings do
    collection do
      post 'update_out_of_stock'
    end
  end

  resources :textbook_deliveries do
    collection do
      post 'create_or_update_textbook'
    end
  end

  resources :course_recommender_usages do
    collection do
      get 'tracking'
    end
  end

  resources :online_mock_exam_attempts, except: [:edit, :update] do
    member do
      get :download
    end
    collection do
      get :refresh_document
    end
    resources :section_attempts, only: [:index, :show] do
      resources :section_item_attempts, only: :index do
        collection do
          put 'complete'
          get 'review'
          put 'update_answer'
        end
        member do
          get :exam_review_videos
          get :exam_review_textbooks
          get :exam_feedback
          get :mcq_exam_question_rating
          post :create_update_question_rating
        end
      end
    end
  end

  resources :online_mock_exam_attempt_temps, except: [:edit, :update] do
    member do
      get :download
    end
    collection do
      get :refresh_document
    end
    resources :section_attempts, only: [:index, :show] do
      resources :section_item_attempts, only: :index do
        collection do
          put 'complete'
          get 'review'
          put 'update_answer'
        end
        member do
          get :exam_review_videos
          get :exam_review_textbooks
          get :exam_feedback
          get :mcq_exam_question_rating
          post :create_update_question_rating
        end
      end
    end
  end

  resources :online_exam_attempts, except: [:edit, :update] do
    collection do
      post 'create_print_exam'
    end
    member do
      get 'print_exam_questions'
      get :print_count
    end
    resources :section_attempts, only: [:index, :show] do
      resources :section_item_attempts, only: :index do
        collection do
          put 'complete'
          get 'review'
          put 'update_answer'
        end
        member do
          get :exam_review_videos
          get :exam_review_textbooks
          get :exam_feedback
          get :mcq_exam_question_rating
          post :create_update_question_rating
        end
      end
    end
  end

  resources :online_mock_exams do
    collection do
      get :archived_online_mock_exams
    end
  end
  resources :online_exams do
    member do
      get :download
      get :change_show_stat
      put :change_lock
      post :duplicate
    end
    resources :sections do
      resources :section_items do
        member do
          delete :remove_question
        end
      end
    end
    collection do
      get :check_position
      get :archived_online_exams
      post :update_product_line_positions
    end
  end

  resources :diagnostic_tests do
    member do
      get :change_show_stat
      put :change_lock
    end
    resources :sections do
      resources :section_items do
        member do
          delete :remove_question
        end
      end
    end
  end

  get 'discount/index'
  get "/exercises/:exercise_id/mcq_attempts/review" => "exercise_review#review", as: :review_exercise_exercise_review
  delete 'exercises/:exercise_id/return_to_mcq' => 'exercise_mcqs#return_to_mcq', as: :return_to_mcq
  post 'exercises/:id/repeat' => 'exercise_mcqs#repeat', as: :repeat
  post 'exercises/review_questions' => 'exercise_mcqs#review_questions', as: :review_questions
  resources :exercises do
    resources :exercise_review, except: [:new, :edit, :create, :edit, :update, :destroy] do
      member do
        get :exercise_review_videos
        get :exercise_review_textbooks
        get :give_feedback
        get :mcq_exam_question_rating
        post :create_update_question_rating
      end
    end
    resources :mcq_attempts, except: [:new, :edit, :create,
            :edit, :update, :destroy] do
      collection do
        put 'update_answer'
        put 'update_mcq_answer'
      end
    end
  end

  resources :job_application_forms, :path => 'jobs' do
    resources :job_applications, :path => 'job-applications' do
      get 'download_all', on: :collection
      get 'get_tag_childrens', on: :collection
      get 'download', on: :member
    end

    get 'archived_jobs', on: :collection
    get 'available-positions', to: 'job_application_forms#available_positions', on: :collection

    get 'show_available_position', on: :member
  end
  resources :job_applications, :path => 'job-applications', only: [] do
    get 'search_applications', on: :collection
    post 'update_interview_date', on: :collection
  end

  # resources :features
  resources :master_features do
    post :master_feature_tags, on: :collection
  end
  # get 'enrolment/:id/' => 'enrolments#show'
  resources :enrolments, only: [:show] do
    member do
      get :student_addon_enrolment
      get :transfer_by
      patch :unenrol_or_renrol
    end
    collection do
      put :attach_enrolment_details
    end
  end

  resources :common_contents, except: [:show, :index]
  resources :free_study_buddies
  resources :study_buddies
  resources :countdown_timers
  resources :download_hit_counters, only: [:index, :edit, :update]
  get 'courses/public_course_cities' => 'courses_filter#public_course_cities'
  get 'courses/filtered_product_versions' => 'courses_filter#filtered_product_versions'
  get 'courses/filtered_transfer_courses' => 'courses_filter#filtered_transfer_courses'

  get 'courses/list_cities' => 'courses_filter#list_cities'
  get 'courses/list_course_lessons' => 'courses_filter#list_course_lessons'
  get 'courses/list_courses_by_city' => 'courses_filter#list_courses_by_city'
  resources :courses do
    get 'enrolments/enrol' => 'enrolments#enrol'
    get 'enrolments/discount_course_enrolment'=> 'enrolments#discount_course_enrolment'
    get 'enrolments/quick_enrol' => 'enrolments#quick_enrol'
    get 'enrolments/student_course_enrolment' => 'enrolments#student_course_enrolment'
    post 'enrolments/paypal_payment' => 'enrolments#paypal_payment'
    post 'enrolments/transfer_payment' => 'enrolments#transfer_payment'
    get 'enrolments/cancel' => 'enrolments#cancel'
    get 'enrolments/transfer_course' => 'enrolments#transfer_course'
    get 'enrolments/custom_enrol' => 'enrolments#custom_enrol'
    
    get :trial_enabled, on: :member
    collection do
      post :set_current_course
      get :archived_courses
      get :get_course_type
    end
    member do
      post :duplicate
      post :unarchived
      get :update_course_id
      get :get_addons
    end
  end
  
  resources :transfer_transactions do
    collection do
      get '/transfer_transaction' => 'transfer_transaction#show'
    end
  end

  get '/users/view_as/:user_id' => 'users#become', as: :view_as
  resources :users, except: [:show, :index] do
    collection do
      get :check_email
      get :check_username
      get :reset_ol_exam
      get :reset_diganostic
      get :reset_essay
      get :reset_mock_exam
      delete :destroy_all
      delete :destroy_ongoing_orders
      get :verify_users
      get :cancel_appointment
      post :study_guide
      post :free_gamsat_trial
      get :reset_online_mock_exam_attempt
      get :display_expiry_date
    end
    resources :enrolments, except: [:index, :show] do
    end
    member do
      get :transfer_data
      put :deactivate
      put :resend_invitation
      get :reset_exams
      get :update_contact
      put :save_detail
      get :course_details
      post :transfer
      get :tutor_interaction_logs
    end
    post :generate_new_password_email

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  layout 'layouts/mathjax'
  layout :resolve_layout
  before_action :authenticate_user!
  before_action :set_exercise, only: [:show, :edit, :update, :destroy]
  before_action :set_service, only: [:new]

  def index
    @exercises = policy_scope(Exercise)
    @exercises = @exercises.order(completed_at: :desc)
    mcq_stems = McqStem.includes(:mcq_attempts).where(mcq_attempts: {id: McqAttempt.where(exercise_id: @exercises.ids).ids})
    @filterrific = initialize_filterrific(
      mcq_stems,
      params[:filterrific],
    ) || return
    if params[:filterrific].present? && params[:filterrific][:search_query].present?
      @mcq_stems = @filterrific.find
      @s_query = true
    else
      @s_query = false
    end
  end

  def new
    if current_user.student? && !current_user.questionnaire.present?
      given_exercises = policy_scope(Exercise)
      mcqs_count = Mcq.includes(:mcq_attempts).where(mcq_attempts: {id: McqAttempt.where(exercise_id: given_exercises.ids).ids}).count
      current_user.update_feature_access_count
      redirect_to dashboard_home_path(update_background: true) and return if current_user.feature_access_count > 3 || mcqs_count > 20
    end
    @announcement, @user_announcement, @exercise, @taggings, @available_tags, @course = @exercise_service.exercise_new(current_course)
    authorize @exercise
  end

  def create
    @course = current_course
    cookies.delete :current_sa if !cookies[:current_sa].nil?
    cookies.delete :current_exe_atmpt if !cookies[:current_exe_atmpt].nil?
    @exercise = current_user.exercises.build(exercise_params)
    @available_tags = current_user.current_feature_tags('McqFeature')
    respond_to do |format|
      if @exercise.save
        @exercise.update_attribute(:timer_option_type, nil) if @exercise.overall_time.nil?
        format.html { redirect_to exercise_mcq_attempts_path(@exercise), notice: 'Exercise was successfully created.' }
        format.json { render :show, status: :created, location: @exercise }
      else
        format.html { render :new }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
        flash[:error] = 'Please review the problems below.'
      end
    end
  end

  def update
    respond_to do |format|
      if @exercise.update(exercise_params)
        format.html { redirect_to @exercise, notice: 'Exercise was successfully updated.' }
        format.json { render :show, status: :ok, location: @exercise }
      else
        format.html { render :edit }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
        flash[:error] = 'Please review the problems below.'
      end
    end
  end

  def destroy
    @exercise.update_mcq_statistics_with_delete(current_course) if @exercise.completed_at.present?
    @exercise.destroy
    respond_to do |format|
      format.html { redirect_to exercises_url, notice: 'Exercise was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_exercise
    @exercise = current_user.exercises.find_by(id: params[:id])
    redirect_to dashboard_home_path and return unless @exercise.present?
  end

  def exercise_params
    params.require(:exercise).permit(:name, :timer_option, :overall_time, :difficulty, :amount, :question_style, :timer_option_type, :course_id,  tag_ids: [])
  end

  def resolve_layout
    'student_page'
  end

  def set_service
    @exercise_service = ExerciseService.new(params, current_user)
  end
end

app/helpers/exercises_helper.rb
module ExercisesHelper
  def tag_level(tag)
    level = 0
    leaf_tag = 0
    leaf_tag += 1 unless Tag.where(parent_id: tag.id).count > 0
    until tag.parent.nil?
      tag = tag.parent
      level += 1
    end
    [level, leaf_tag]
  end

  def tag_level_row_style(level, leaf_tag, score, viewed=nil)
    return if viewed.present? && viewed == 0
    score = score.to_i
    if leaf_tag >= 0
      if score >= 0 && score < 50
        'color_red'
      elsif score >= 50 && score < 70
        'color_orange'
      elsif score >= 70 && score <= 100
        'color_green'
      end
    end
  end

  def score_by_tag(statistics, tag)
    correct_mcq = statistics[tag.id]['correct_mcq_by_tag'].to_f
    viewed_mcq = statistics[tag.id]['viewed_mcq_by_tag'].to_f
    (correct_mcq / viewed_mcq * 100).nan? ? '0.0%' : number_to_percentage((correct_mcq / viewed_mcq * 100), precision: 1)
  end

  def score_by_tag_statistics(tag, by_tag_correct, by_tag_total)
    correct_mcq = by_tag_correct.to_f
    (correct_mcq / by_tag_total * 100).nan? ? '0.0%' : number_to_percentage((correct_mcq / by_tag_total * 100), precision: 1)
  end

  def total_mcq_by_tag(statistics, tag)
    statistics[tag.id]['total_mcq_by_tag']
  end

  def viewed_mcq_by_tag(statistics, tag)
    statistics[tag.id]['viewed_mcq_by_tag']
  end

  def correct_mcq_by_tag(statistics, tag)
    statistics[tag.id]['correct_mcq_by_tag']
  end

  def get_difficulties
    difficulty_titles = { easy: 'Easy',
                          medium: 'Medium',
                          hard: 'Hard',
                          mixed: 'Mix of All Difficulty Levels' }
    Exercise.difficulties.keys.map { |k| [difficulty_titles[k.to_sym], k] }
  end

  def tag_level_padding(level)
    level == 2 ? 'tag-level2-padding' : level == 1 ? 'tag-level1-padding' : ''
  end
end

app/views/exercises/_mcq_stems.html.haml
-if mcq_stems.present?
  .text_btn_rght_col
    %h4 Questions
  %table.table.table-bordered.table-hover.essay_table.exer-table
    %thead
      %tr
        %th.exercise_flr_mcq Title
        %th.exercise_flr_mcq{colspan: 1} Action

    %tbody
      - mcq_stems.each do |mcq_stem|
        %tr
          %td= mcq_stem.title
          %td
            %a.table_icon_col{"data-placement" => "top", title: "Review", "data-toggle" => "tooltip", href: review_exercise_exercise_review_path(exercises.includes(:mcq_stems).find_by(mcq_stems: {id: mcq_stem.id}))}
              = image_tag 'https://gradready.s3.ap-southeast-2.amazonaws.com/static/student_pages/review_icon.svg'
-elsif s_query
  .alert.alert-warning.nothing_found Nothing found
-else
  .text_btn_rght_col
    %h4 Listing Exercises
    = link_to 'New Exercise', new_exercise_path, class: 'default_btn hvr-shutter-in-horizontal', onclick: 'dd_loader();'
  -if @exercises.present?
    -if request.variant.blank?
      %table.table.mobile_data_table.table-bordered.table-hover.essay_table.exer-table
        %thead
          %tr
            %th Name
            %th Difficulty
            %th Amount Available
            %th Completed
            %th Action

        %tbody
          - @exercises.each do |exercise|
            - exercise.add_attempted_mcqs if exercise.attempted_mcqs.blank?
            %tr
              %td= exercise.name
              %td= exercise.difficulty
              %td= exercise.mcqs.count
              %td= exercise.completed_at.in_time_zone('Sydney').to_formatted_s(:long) if exercise.completed_at
              %td
                %span.exercise_btns
                  - if exercise.completed_at.present?
                    = link_to image_tag('https://gradready.s3.ap-southeast-2.amazonaws.com/static/student_pages/resit_icon.svg'), repeat_path(id: exercise.id), method: :post, data: { confirm: 'Are you sure?', placement: 'top', toggle: 'tooltip', title: 'Resit'}, class: 'table_icon_col'
                %span.exercise_btns
                  = link_to image_tag('https://gradready.s3.ap-southeast-2.amazonaws.com/static/student_pages/delete_icon.svg'), exercise_path(exercise), method: :delete, data: { confirm: 'Are you sure?', placement: 'top', toggle: 'tooltip', title: 'Delete'}, class: 'table_icon_col'
                %span.exercise_btns
                  -if exercise.completed_at.nil?
                    - cea_data = JSON.parse(cookies[:current_exe_atmpt]) if !cookies[:current_exe_atmpt].blank?
                    - cea_data = JSON.parse(cookies[:current_sa]) if !cookies[:current_sa].blank?
                    - if !cookies[:current_sa].blank? || !cookies[:current_exe_atmpt].blank?
                      = link_to image_tag('https://gradready.s3.ap-southeast-2.amazonaws.com/static/student_pages/start_icon.svg'), exercise_mcq_attempts_path(exercise), data: { confirm: "You are trying to create a new “ #{exercise.name} ”, would you like to cancel the paused #{cea_data['name']} ?Please click Ok if you would like to create new attempt or press Cancel if you would like to continue.", placement: 'top', toggle: 'tooltip', title: 'Start'}, onclick: 'dd_loader();'
                    - else
                      = link_to image_tag('https://gradready.s3.ap-southeast-2.amazonaws.com/static/student_pages/start_icon.svg'), exercise_mcq_attempts_path(exercise), class: 'table_icon_col', data: { placement: 'top', toggle: 'tooltip', title: 'Start'}, onclick: 'dd_loader();'
                  -else
                    = link_to image_tag('https://gradready.s3.ap-southeast-2.amazonaws.com/static/student_pages/review_icon.svg'), exercise_path(exercise), class: 'table_icon_col', data: { placement: 'top', toggle: 'tooltip', title: 'Review'}, onclick: 'dd_loader();'
    -if request.variant == [:phone]
      .mobile_table_border
        %ul.tbl_head
          %li.width_inc Name
          %li.mobile_wdt_th.mobile_wdt_th74.rht16.mobile_mousehover_tool
            Action
        - @exercises.each do |exercise|
          %ul.mobile_table_body.listing.tbl_head.exercise_bdr_none
            %li.mobile_mousehover_tool.width_inc
              = exercise.name
              %ul.tool_tip
                %li= "Difficulty: #{exercise.difficulty}"
                %li= "Amount Available: #{exercise.amount}"
                %li= "Completed: #{exercise.completed_at.in_time_zone('Sydney').to_formatted_s(:long) if exercise.completed_at}"
                %li
                  - if exercise.completed_at.present?
                    = link_to image_tag('https://gradready.s3.ap-southeast-2.amazonaws.com/static/student_pages/resit_icon.svg'), repeat_path(id: exercise.id), method: :post, data: { confirm: 'Are you sure?', placement: 'top', toggle: 'tooltip', title: 'Resit'}, class: 'table_icon_col', onclick: 'dd_loader();'
                  = link_to image_tag('https://gradready.s3.ap-southeast-2.amazonaws.com/static/student_pages/delete_icon.svg'), exercise_path(exercise), method: :delete, data: { confirm: 'Are you sure?', placement: 'top', toggle: 'tooltip', title: 'Delete'}, class: 'table_icon_col', onclick: 'dd_loader();'
                  -if exercise.completed_at.nil?
                    - cea_data = JSON.parse(cookies[:current_exe_atmpt]) if !cookies[:current_exe_atmpt].blank?
                    - cea_data = JSON.parse(cookies[:current_sa]) if !cookies[:current_sa].blank?
                    - if !cookies[:current_sa].blank? || !cookies[:current_exe_atmpt].blank?
                      = link_to image_tag('https://gradready.s3.ap-southeast-2.amazonaws.com/static/student_pages/start_icon.svg'), exercise_mcq_attempts_path(exercise), class: 'table_icon_col', data: { confirm: "You are trying to create a new “ #{exercise.name} ”, would you like to cancel the paused #{cea_data['name']} ?Please click Ok if you would like to create new attempt or press Cancel if you would like to continue.", placement: 'top', toggle: 'tooltip', title: 'Start'}, onclick: 'dd_loader();'
                    - else
                      = link_to image_tag('https://gradready.s3.ap-southeast-2.amazonaws.com/static/student_pages/start_icon.svg'), exercise_mcq_attempts_path(exercise), class: 'table_icon_col', data: { placement: 'top', toggle: 'tooltip', title: 'Start'}, onclick: 'dd_loader();'
                  -else
                    = link_to image_tag('https://gradready.s3.ap-southeast-2.amazonaws.com/static/student_pages/review_icon.svg'), exercise_path(exercise), class: 'table_icon_col', data: { placement: 'top', toggle: 'tooltip', title: 'Review'}, onclick: 'dd_loader();'
            %li.mobile_mousehover_tool.mobile_wdt_th.mobile_wdt_th74.rht16
              -if exercise.completed_at.nil?
                - cea_data = JSON.parse(cookies[:current_exe_atmpt]) if !cookies[:current_exe_atmpt].blank?
                - cea_data = JSON.parse(cookies[:current_sa]) if !cookies[:current_sa].blank?
                - if !cookies[:current_sa].blank? || !cookies[:current_exe_atmpt].blank?
                  = link_to image_tag('https://gradready.s3.ap-southeast-2.amazonaws.com/static/student_pages/start_icon.svg'), exercise_mcq_attempts_path(exercise), data: { confirm: "You are trying to create a new “ #{exercise.name} ”, would you like to cancel the paused #{cea_data['name']} ?Please click Ok if you would like to create new attempt or press Cancel if you would like to continue."}, class: 'table_icon_col', onclick: 'dd_loader();'
                  %span.heading_tool_tip.mrht37
                    %p Start
                - else
                  = link_to image_tag('https://gradready.s3.ap-southeast-2.amazonaws.com/static/student_pages/start_icon.svg'), exercise_mcq_attempts_path(exercise), class: 'table_icon_col', onclick: 'dd_loader();'
                  %span.heading_tool_tip.mrht37
                    %p Start
              -else
                = link_to image_tag('https://gradready.s3.ap-southeast-2.amazonaws.com/static/student_pages/review_icon.svg'), exercise_path(exercise), class: 'table_icon_col', onclick: 'dd_loader();'
                %span.heading_tool_tip.mrht37
                  %p Review
  -else
    .alert.alert-warning.nothing_found Nothing found
:javascript
  $(".mobile_mousehover_tool").click(function(){
    $(".mobile_mousehover_tool").removeClass("acitve");
    $(this).addClass("acitve");
    $(".overlay_show").addClass("show_tool_wrapper");
  });

app/views/exercises/_mcq_tag_info.html.haml
%ul.tbl_head.listing{class: "#{score_class}"}
  %li.width_inc
    - selected_tags = params[:exercise].present? ? params[:exercise][:tag_ids].present? ? params[:exercise][:tag_ids].include?(tag.id.to_s) : nil : nil
    = check_box_tag 'exercise[tag_ids][]', tag.id, selected_tags, data: {   autocheck_ids: tag.children.pluck(:id).join(',') }, id: "exercise_tag_ids_#{tag.id}"
    %label{for: "exercise_tag_ids_#{tag.id}"}= tag.name
    %span.mobile_mousehover_tool
      %span.mobile_data_label_show= tag.name
      %span.heading_tool_tip
        %p= tag.name
      %ul.tool_tip.checkbox_tool_tip
        %li="Total: #{mcq_stat.total}"
        %li="Viewed: #{mcq_stat.viewed}"
        %li="Correct: #{mcq_stat.correct}"
        %li="Used: #{mcq_stat.used.to_s + '%'}"
        %li="Score: #{mcq_stat.score.to_s + '%'}"
  %li.mobile_wdt_th.rht56= mcq_stat.used.round.to_s + '%'
  %li.mobile_wdt_th.rht15= mcq_stat.score.round.to_s + '%'
  %li= mcq_stat.total
  %li= mcq_stat.viewed
  %li= mcq_stat.correct
  %li= mcq_stat.used.to_s + '%'
  %li= mcq_stat.score.to_s + '%'

app/views/exercises/_tagging_fields.html.haml
.nested-fields
  = f.association :tag
  = link_to_remove_association 'remove tag', f

app/views/exercises/edit.html.haml
%h1 Editing exercise

= render 'form'

= link_to 'Show', @exercise, onclick: 'dd_loader();'
\|
= link_to 'Back', exercises_path, onclick: 'dd_loader();'

app/views/exercises/index.js.erb
<% js = escape_javascript(render(partial: 'exercises/mcq_stems', locals: { mcq_stems: @mcq_stems, exercises: @exercises, s_query: @s_query }))%>
$("#filterrific_results").html("<%= js %>");

app/views/exercises/show.html.haml
- content_for :page_heading, 'Mcq Attempt'
.dashbord_right
  .resource_col.mbot21
    %h4.fl MCQ Attempt
  .statics_static_table
    %ul
      %li
        %span Difficulty of Questions :
        = @exercise.difficulty
      %li
        %span Number of Questions :
        = @exercise.amount
      %li
        %span Completed at :
        = @exercise.completed_at ? @exercise.completed_at.to_formatted_s(:long) : "N/A"
      %li
        %span Percent Correct :
        = number_to_percentage(@exercise.percentage, precision: 1) || "N/A"

  .faq_list
    .faq_list_col.table_3_col
      .new_excercise
        %h4 Statistics
        %ul.indicator.excercise_indictor
          %li
            %i.fa.fa-frown-o{"aria-hidden" => "true"}
            \&lt;50%
          %li
            %i.fa.fa-frown-o{"aria-hidden" => "true"}
            50% - 69.99%
          %li
            %i.fa.fa-smile-o{"aria-hidden" => "true"}
            70% - 100%
      .excercise_tbl.satatics_table
        %ul.tbl_head
          %li.width_inc Name
          %li.mobile_wdt_th.rht56.mobile_mousehover_tool
            C
            %span.heading_tool_tip.mrht37
              %p Correct
          %li.mobile_wdt_th.rht15.mobile_mousehover_tool
            I
            %span.heading_tool_tip.mrht37
              %p Incorrect
          %li.wdth6 Correct
          %li.wdth6 Incorrect
          %li.wdth6
            Not
            = succeed "Attempted" do
              %br/
          %li.wdth6 Total
          %li
            Time Taken
            = succeed "(Min)" do
              %br/
          %li
            Time taken
            %br/
            per question (Min)
        .first_child_section
          - @exercise.tags.sort_by{|tag| tag.name}.each do |q|
            - result = @exercise.show_tag_result q
            - if result['total'] > 0
              - level,leaf_tag = tag_level(q)
              - score_class = tag_level_row_style(level, leaf_tag, score_by_tag_statistics(q, result['correct'], result['total']), (result['total']-result['not_attempted']) )

              -if level == 1
                .second_child_section
                  = render 'mcq_tag_result', tag: q, result: result, score_class: score_class
              -elsif level == 2
                .second_child_section
                  .third_child_section
                    = render 'mcq_tag_result', tag: q, result: result, score_class: score_class
              -else
                = render 'mcq_tag_result', tag: q, result: result, score_class: score_class


      .text-center.full_width.mtop30.mbot10
        = link_to 'Review', review_exercise_exercise_review_path(@exercise), class: 'default_btn hvr-shutter-in-horizontal', onclick: 'dd_loader();'
        = link_to 'Back', exercises_path, class: 'black_default_btn resp_btn hvr-shutter-in-horizontal', onclick: 'dd_loader();'